### PR TITLE
Fixes contact script and Adds jasmine test suite (for ReadingModes)

### LINKED ISSUE #18: Add test suite and create tests for ReadingModes

### PR DESCRIPTION
**Pull request by andr3**
Closes #18

### CODE REVIEW

File: assets/js/ReadingModes.js [hunk 1]
```diff
@@ -4,6 +4,7 @@ ReadingModes = function (element) {
     this.element.siblings('input').on('focus', $.proxy(this.handleInputChange, this));
 
     this.enableKeys();
+    this.activate('full', {animate: false}); // default
```
Comment (andr3) [inline assets/js/ReadingModes.js]: sdfsdfsdf

**Review by andr3 — COMMENTED** [review]
sddfsds
